### ISSUE TITLE
[Analytics] CONP Analytics - phase 1

### ISSUE THREAD

**Issue by paiva** [CONP-PCNO/conp-portal#14]
### Summary of the analytics to be added on the short term from our Matomo server (Feb 23rd, 2021)

- [x] display Matomo widgets directly into the analytics page using iframes #403
- [x] display number of visits to the portal across time #404
- [x] display number of views per datasets/tools #405
- [x] display popular keyword searches #406 
- [ ] display analytics on dataset providers #407

### Old description of the ticket (Mar 11, 2019)

It would be ideal to deploy some analytics tool and some event tracking systems to better understand user behavior and, if possible, find out what it is being done with the data downloaded. 

Event tracking tags should be consistent with those to be used by the LORIS platform so that we are consistent across both platforms.

Some event tracking tools include:
* Google Analytics
* Snowplow Analytics
* Piwik
* Google WebMaster Tools

Some dashboard tools include:
* Google Analytics
* Grafana

**Comment by paiva** [comment]
@shots47s What is CBRAIN doing for tracking analytics?

**Comment by shots47s** [comment]
@paiva, we use our own internal mechanisms that are baked into the server code.  I would not recommend doing that, I would use something that is canned and out of the box.  I have used GA before, and it works really nice, I know some may have some issues with it being Google, but you can close off sections of the website to the analytics.  I don't have experience with the others.

**Comment by maltheism** [comment]
Hey @paiva, as you know there is discussion of adding GA to LORIS. So let's stay in sync. We can definitely limit what pages GA has access over by not loading it on certain pages.

**Comment by xlecours** [comment]
Matomo (formerly known as Piwik) is free as in freedom (GPLv3)

**Comment by cmadjar** [comment]
Discussed at CONP dev meeting on May 20th, 2020.

What would be next highest priority analytics?
- analytics to display on the portal
  - how many datasets available
  - number of tools available
  - more popular datasets on the portal

- analytics to collect for reviewers and Brain Canada
  - how many datasets visited, how many datasets downloaded etc...?
  - number of users, visits etc..

for next week, prepare a document with metrics of interests.

**Comment by glatard** [comment]
Idea for a metric:
[ ] Number of git clones of the `conp-dataset` repo: https://github.com/CONP-PCNO/conp-dataset/graphs/traffic

**Comment by cmadjar** [comment]
A few ideas of metrics (mostly basic I guess but always good to write them down):
1. [ ] **Number of datasets and tools**
2. [ ] Keyword search (to gather some stats on what people are looking for maybe) - not sure how easy to gather that though....
3. [ ] **_Number of git clones of the conp-dataset repo (from @glatard above, just gathering everything in one description so far)_**
4. [ ] Number of pipelines run through CBRAIN (and number of datasets processed through CBRAIN)
5. [ ] _Number of uploads through the different upload platforms (Zenodo, OSF, FRDR, DataLad...) (not sure if useful, maybe for Brain Canada)_
6. [ ] **_Graphical representation of some predefined modality key words. For example, number of dataset with EEG, number of quality control subject datasets, number of dataset with MRI etc..._**
7. [ ] **_Graphical representation of some predefined Tags for the tools. For example, number of bioinformatics tools, neuroinformatics tools, MRI tool etc..._**
8. [ ] Number of open datasets, open datasets requiring an account, registered datasets ...

legend: 
- **bold** = general stats that could be represented on the portal (dashboard or somewhere else)
- _italic_ = some stats that could be of interest for Brain Canada

**Comment by jbpoline** [comment]
Add #views and #download click per dataset

**Comment by cmadjar** [comment]
[ ] Number of datasets and tools on the dashboard
[ ] Graphical representation of modality key words. For example, number of dataset with EEG, number of quality control subject datasets, number of dataset with MRI etc...
[ ] Graphical representation of Tags for the tools. For example, number of bioinformatics tools, neuroinformatics tools, MRI tool etc..
[ ] Number of views of the different visited pages of the portal 
[ ] Keyword search statistics (to gather some stats on what people are looking for on the datasets and tools pages)
[ ] List of institutions that provided the datasets (a little map with dots)


Long term:
[ ] Number of times download has been clicked on when available
[ ] Number of uploads through the different upload platforms (Zenodo, OSF, FRDR, DataLad...) (not sure if useful, maybe for Brain Canada)
[ ] Number of pipelines run through CBRAIN (and number of datasets processed through CBRAIN)
[ ] Where the users come from (to be checked with terms of use too...)

**Comment by cmadjar** [comment]
Deadline for phase 1 of analytics: End of July 2020. See which analytics in the comment made 7 days ago.

**Comment by cmadjar** [comment]
Summary of the discussions that happened during a quick meeting between @3design, @liamocn and @cmadjar on July 8th, 2020.

Overall representation of the analytics:
1) in the dashboard:
  a) in the card showing the graph, add a drop down where users can select which representation they want to see on that card with the ability to visualize the selected graph in the card
  b) at the bottom of the card, add a square button that would lead to an analytics page that would display all the analytics available
2) create an analytics page that will display all the graphs in the page. When we will have a lot of graphs, they could be organized per subject (data, tools, user's based statistics...)

Different graphs to work on:
- start with the representation of keyword/tags for the datasets and tools present in CONP
  - for dataset, representation of the modality keywords: use the `types` section of the DATS model to show the number of each modality keyword across all datasets (aka: number of EEG, number of MRI, number of BIDS, number of behavrioral response...)
  - for tools: use the `tags` present in the Boutiques descriptor and represent the number of each tag
- regarding the users experience on the portal (number of views, keyword search hits...), we need to figure out how to track the number of clicks, dataset viewed etc...
- for the list of institutions to be represented on a map, we don't currently have that information available. Will need to update the DATS model to require a field that would describe the institution and its address.
  - in the meantime, we could have a representation of the conp_status field if that is of interest (`CONP`, `Canadian` or `external`)

@3design @liamocn feel free to add or correct my notes on the meeting we just had. We will present that at the next CONP dev meeting so everyone is on board with the plan.

**Comment by cmadjar** [comment]
Discussed at CONP dev meeting of July 15th, 2020:

- Regarding the map graph, there is a proposal to broaden the range of values for CONP_status, see https://github.com/CONP-PCNO/conp-dataset/issues/366

- Webiste traffic: could set up Google analytics to run on the portal if this goes with the CONP terms of use (to be followed up with the ethics and governance committee). Could also parse the logs in the server or set up JS counters...

- Ideas to count downloads:
  - Count the number of access to the dataset web page 
  - Count them through the web download button
  - Count the number of git clones using the GitHub API
  - Instrument the DataLad client to report download stats

**Comment by cmadjar** [comment]
@liamocn updates from today's meeting:

- Match dataset and pipeline colours from the first graph with the dataset and pipeline bubble charts colours
- Use a different colour than grey for pipelines (pick from the CONP palette)
- Fix the `View analytics` button not working on Firefox
- Remove the `Select Chart` drop down from the dashboard

Is that something you could do this quickly to have that ready for the next CONP dev meeting?

**Comment by cmadjar** [comment]
Because this ticket is like a gigantic ticket, it has been split into several smaller tickets:
- Display Matomo widgets into the analytics page, #403 (visitors map, page transitions etc...)
- Display number of visits to the portal across time, #404 **_(to be discussed)_**
- Display number of views per datasets/tools, #405
- List popular keyword searches, #406
- Analytics on dataset providers, #407
